# Generated by Django 3.0.4 on 2020-03-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_readprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_time',
            field=models.IntegerField(blank=True),
        ),
    ]
