# Generated by Django 3.0.4 on 2020-03-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200329_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_time',
            new_name='birth_year',
        ),
    ]
