# Generated by Django 3.0.4 on 2020-03-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200329_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
